from __future__ import unicode_literals

ABBRE = {
    'mtqt': 'mặt_trận_tổ_quốc',
    'ubnd': 'ủy_ban_nhân_dân',
    'btl_bdbp': 'bộ_tư_lệnh_bộ_đội_biên_phòng',
    'btl': 'bộ_tư_lệnh',
    'nd': 'nhân_dân',
    'ksv': 'kiểm_soát_viên',
    'nk': 'nhập_khẩu',
    'xk': 'xuất_khẩu',
    'xnk': 'xuất_nhập_khẩu',
    'cbcc': 'cán_bộ_công_chức',
    'SDLĐ': 'sử_dụng_lao_động',
    'CMKTNN': 'kiểm_toán_nhà_nước',
    'NHNN': 'ngân_hàng_nhà_nước',
    'BMTT': 'bảo_mật_thông_tin',
    'PTBVCN': 'phương_tiện_bảo_vệ_cá_nhân',
    'KHKT' : 'khoa_học_kỹ_thuật',
    'edu': 'giáo_dục',
    'EHSDT': 'quy_trình_đánh_giá_hồ_sơ_dự_thầu',
    'HSDT': 'hồ_sơ_dự_thầu',
    'HSMT': 'hồ_sơ_mời_thầu',
    'HSMC': 'hồ_sơ_mời_chào',
    'KHCN': 'khoa_học_công_nghệ',
    'KHCN&MT': 'khoa_học_công_nghệ_môi_trường',
    'KHCN&MT&TT': 'khoa_học_công_nghệ_môi_trường_thông_tin',
    'TNMT': 'tài_nguyên_môi_trường',
    'TN&MT': 'tài_nguyên_môi_trường',
    'TTTT': 'thông_tin_truyền_thông',
    'TTDPT': 'truyền_thông_đa_phương_tiện',
    
}
CURRENCY = {
    '0.000': 'nghìn',
    '00.000': 'trăm',
    '000.000': 'triệu',
    '0.000.000': 'chục_triệu',
    '000.000.000': 'trăm_triệu',
    '000.000.000': 'tỷ',
    '0.000.000.000': 'chục_tỷ',
    '00.000.000.000': 'trăm_tỷ',
    '000.000.000.000': 'nghìn_tỷ',
    'chục triệu': 'chục_triệu',
    'trăm triệu': 'trăm_triệu',
    'chục tỷ': 'chục_tỷ',
    'trăm tỷ': 'trăm_tỷ',
    'nghìn tỷ': 'nghìn_tỷ'
}
PROVINCES = {
    "An_Giang", "Bà_Rịa_Vũng_Tàu","Vũng_Tàu", "Bạc_Liêu", "Bắc_Kạn", "Bắc_Giang", "Bắc_Ninh",
    "Bến_Tre", "Bình_Dương", "Bình_Định", "Bình_Phước", "Bình_Thuận", "Cà_Mau", 
    "Cần_Thơ", "Cao_Bằng", "Đà_Nẵng", "Đắk_Lắk", "Đắk_Nông", "Điện_Biên","Hà_Nam", "Đồng_Nai", 
    "Đồng_Tháp", "Gia_Lai", "Hà_Giang", "Hà_Nội", "Hà_Tĩnh", "Hải_Dương", 
    "Hải_Phòng", "Hậu_Giang", "Hòa_Bình", "Hưng_Yên", "Khánh_Hòa", "Kiên_Giang", 
    "Kon_Tum", "Lai Châu", "Lào_Cai", "Lâm_Đồng", "Lạng_Sơn","Long_An", "Nam_Định", 
    "Nghệ_An", "Ninh_Bình", "Ninh_Thuận", "Phú_Thọ", "Phú_Yên", "Quảng_Bình", 
    "Quảng_Nam", "Quảng_Ngãi", "Quảng_Ninh", "Quảng_Trị", "Sóc_Trăng", "Sơn_La", 
    "Tây Ninh", "Thái_Bình", "Thái_Nguyên", "Thanh_Hóa", "Thừa_Thiên_Huế", "Tiền_Giang", 
    "TP_Hồ_Chí_Minh", "Trà_Vinh", "Tuyên_Quang", "Vĩnh_Long", "Vĩnh_Phúc", "Yên_Bái"
}
LEGAL_WORDs = {
    "luật pháp": "luật_pháp",
    "hiến pháp": "hiến_pháp",
    "tư pháp": "tư_pháp",
    "căn cứ": "căn_cứ",
    "cơ sở pháp lý": "cơ_sở_pháp_lý",
    "điều khoản": "điều_khoản",
    "hiệu lực": "hiệu_lực",
    "thẩm quyền": "thẩm_quyền",
    "ban hành": "ban_hành",
    "đình chỉ": "đình_chỉ",
    "hành chính": "hành_chính",
    "quy định": "quy_định",
    "nghị định": "nghị_định",
    "quy phạm": "quy_phạm",
    "chỉ thị": "chỉ_thị",
    "xét xử": "xét_xử",
    "bồi thường": "bồi_thường",
    "hòa giải": "hòa_giải",
    "trách nhiệm": "trách_nhiệm",
    "nghĩa vụ": "nghĩa_vụ",
    "quyền lợi": "quyền_lợi",
    "tài sản": "tài_sản",
    "hôn nhân": "hôn_nhân",
    "hợp đồng": "hợp_đồng",
    "cam kết": "cam_kết",
    "thỏa thuận": "thỏa_thuận",
    "giao dịch": "giao_dịch",
    "mua bán": "mua_bán",
    "tặng cho": "tặng_cho",
    "vay nợ": "vay_nợ",
    "thế chấp": "thế_chấp",
    "cầm cố": "cầm_cố",
    "ủy quyền": "ủy_quyền",
    "doanh nghiệp": "doanh_nghiệp",
    "công ty": "công_ty",
    "cổ phần": "cổ_phần",
    "điều lệ": "điều_lệ",
    "giấy phép": "giấy_phép",
    "đăng ký": "đăng_ký",
    "pháp nhân": "pháp_nhân",
    "vi phạm pháp luật": "vi_phạm_pháp_luật",
    "bồi thường thiệt hại": "bồi_thường_thiệt_hại",
    "thi hành án": "thi_hành_án",
    "tự do ngôn luận": "tự_do_ngôn_luận",
    "pháp lý": "pháp_lý",
    "tài sản thế chấp": "tài_sản_thế_chấp",
    "tài sản đảm bảo": "tài_sản_đảm_bảo",
    "chuyển nhượng đất đai": "chuyển_nhượng_đất_đai",
    "quyền sở hữu": "quyền_sở_hữu",
    "trách nhiệm hữu hạn": "trách_nhiệm_hữu_hạn",
    "chế tài hành chính": "chế_tài_hành_chính",
    "quyền lợi người lao động": "quyền_lợi_người_lao_động",
    "biện pháp cưỡng chế": "biện_pháp_cưỡng_chế",
    "tố tụng hình sự": "tố_tụng_hình_sự",
    "vi phạm hành chính": "vi_phạm_hành_chính",
    "quy chế hoạt động": "quy_chế_hoạt_động",
    "hợp đồng lao động": "hợp_đồng_lao_động",
    "tập trung dân chủ": "tập_trung_dân_chủ",
    "hợp đồng dân sự": "hợp_đồng_dân_sự",
    "hành lang pháp lý": "hành_lang_pháp_lý",
    "tuyên giáo trung ương": "tuyên_giáo_trung_ương",
    "chứng minh nhân dân": "chứng_minh_nhân_dân",
    "biên bản vi phạm": "biên_bản_vi_phạm",
    "luật doanh nghiệp": "luật_doanh_nghiệp",
    "đăng ký kinh doanh": "đăng_ký_kinh_doanh",
    "bảo hiểm xã hội": "bảo_hiểm_xã_hội",
    "bảo hiểm nhân thọ": "bảo_hiểm_nhân_thọ",
    "bảo hiểm hưu trí": "bảo_hiểm_hưu_trí",
    "bảo hiểm tử kỳ": "bảo_hiểm_tử_kỳ",
    "tội phạm ma túy": "tội_phạm_ma_túy",
    "bảo lãnh ngân hàng": "bảo_lãnh_ngân_hàng",
    "báo cáo tài chính": "báo_cáo_tài_chính",
    "an ninh mạng": "an_ninh_mạng",
    "vốn đầu tư": "vốn_đầu_tư",
    "mẫu biểu": "mẫu_biểu",
    "kế toán thuế": "kế_toán_thuế",
    "hộ gia đình": "hộ_gia_đình",
    "tái đầu tư": "tái_đầu_tư",
    "tàng trữ trái phép": "tàng_trữ_trái_phép",
    "văn hóa phẩm đồi trụy": "văn_hóa_phẩm_đồi_trụy",
    "tòa án nhân dân": "tòa_án_nhân_dân",
    "báo động lũ": "báo_động_lũ",
    "bổ sung": "bổ_sung",
    "thay thế": "thay_thế",
    "gia hạn": "gia_hạn",
    "tước quyền": "tước_quyền",
    "tịch thu": "tịch_thu",
    "cảnh cáo": "cảnh_cáo",
    "phạt nguội": "phạt_nguội",
    "kê khai": "kê_khai",
    "chứng từ": "chứng_từ",
    "thủ tục": "thủ_tục",
    "biên bản": "biên_bản",
    "báo cáo": "báo_cáo",
    "cá nhân": "cá_nhân",
    "tổ chức": "tổ_chức",
    "tiêu chí": "tiêu_chí",
    'nguyên tắc': 'nguyên_tắc',
    'kỳ hạn': "kỳ hạn",
    "tờ trình": "tờ_trình",
    "tường trình": "tường_trình",
    "bổn_phận": "bổn_phận",
    "đảm bảo": "đảm_bảo",
    "hạn mức": "hạn_mức",
    "hạn định": "hạn_định",
    "gia hạn": "gia_hạn",
    "hết hạn": "hết_hạn",
    "luật xuất nhập khẩu": "luật_xuất_nhập_khẩu",
    "hàng hóa": "hàng_hóa",
    "phi thuế quan": "phi_thuế_quan",
    "phạm vi áp dụng": "phạm_vi_áp_dụng"
}
ROMAN_NUM= {
    'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X',
    'XI', 'XII', 'XIII', 'XIV', 'XV', 'XVI', 'XVII', 'XVIII', 'XIX', 'XX',
    'XXI', 'XXII', 'XXIII', 'XXIV', 'XXV', 'XXVI', 'XXVII', 'XXVIII', 'XXIX', 'XXX',
    'XXXI', 'XXXII', 'XXXIII', 'XXXIV', 'XXXV', 'XXXVI', 'XXXVII', 'XXXVIII', 'XXXIX', 'XL',
    'XLI', 'XLII', 'XLIII', 'XLIV', 'XLV', 'XLVI', 'XLVII', 'XLVIII', 'XLIX', 'L',
    'LI', 'LII', 'LIII', 'LIV', 'LV', 'LVI', 'LVII', 'LVIII', 'LIX', 'LX',
    'LXI', 'LXII', 'LXIII', 'LXIV', 'LXV', 'LXVI', 'LXVII', 'LXVIII', 'LXIX', 'LXX',
    'LXXI', 'LXXII', 'LXXIII', 'LXXIV', 'LXXV', 'LXXVI', 'LXXVII', 'LXXVIII', 'LXXIX', 'LXXX',
    'LXXXI', 'LXXXII', 'LXXXIII', 'LXXXIV', 'LXXXV', 'LXXXVI', 'LXXXVII', 'LXXXVIII', 'LXXXIX', 'XC',
    'XCI', 'XCII', 'XCIII', 'XCIV', 'XCV', 'XCVI', 'XCVII', 'XCVIII', 'XCIX', 'C'
}
SPECIAL_TERMS = {
    'trở lên': 'trở_lên',
    'nâng cao': 'nâng_cao',
    'đến mức': 'đến_mức',
    'quá mức': 'quá_mức',
    'vượt mức': 'vượt mức',
    'suy giảm': 'suy_giảm',
    'tăng cường': 'tăng_cường',
    'tăng giảm': 'tăng_giảm',
    'tăng lên': 'tăng_lên',
    'giảm xuống': 'giảm_xuống',
    'giảm dần': 'giảm_dần',
    'giảm bớt': 'giảm_bớt',
    'giảm thiểu': 'giảm_thiểu',
    'giảm nhẹ': 'giảm_nhẹ',
    'giảm giá': 'giảm_giá',
    'giảm giá thành': 'giảm_giá_thành',
    'giảm thuế': 'giảm_thuế'
}